/*
 * MGRS → lat/lon vs an independent oracle (python `mgrs` lib) across the Swedish
 * UTM zones (33U/V/W, 34U/V/W) + the two real example grids.
 */
import { strict as assert } from "node:assert";
import { test } from "node:test";
import { mgrsToLatLon, findMgrsLatLon } from "../src/mgrs.ts";

// Oracle: { mgrs -> lat, lon } generated by python mgrs.toLatLon.
const ORACLE: Array<{ mgrs: string; lat: number; lon: number }> = [
  { mgrs: "33UUB4209153273", lat: 55.499999, lon: 12.499993 },
  { mgrs: "33UWB0000050433", lat: 55.499998, lon: 15.0 },
  { mgrs: "33UXB7053853745", lat: 55.499993, lon: 17.699999 },
  { mgrs: "34UDG0524751455", lat: 55.499996, lon: 19.499985 },
  { mgrs: "34UEG0000050433", lat: 55.499998, lon: 21.0 },
  { mgrs: "33VUE5224731444", lat: 57.999995, lon: 12.499992 },
  { mgrs: "33VWE0000028710", lat: 57.999999, lon: 15.0 },
  { mgrs: "33VXE5956831899", lat: 57.999996, lon: 17.699983 },
  { mgrs: "34VDK1134029694", lat: 57.999996, lon: 19.49999 },
  { mgrs: "34VEK0000028710", lat: 57.999999, lon: 21.0 },
  { mgrs: "33VUF5776779468", lat: 59.329997, lon: 12.49999 },
  { mgrs: "33VWF0000076798", lat: 59.329994, lon: 15.0 },
  { mgrs: "33VXF5360779912", lat: 59.329995, lon: 17.699998 },
  { mgrs: "34VDL1465277759", lat: 59.329994, lon: 19.499996 },
  { mgrs: "34VEL0000076798", lat: 59.329994, lon: 21.0 },
  { mgrs: "33VUH6268709705", lat: 60.499999, lon: 12.499987 },
  { mgrs: "33VWH0000007097", lat: 60.499998, lon: 15.0 },
  { mgrs: "33VXH4829310139", lat: 60.499999, lon: 17.699996 },
  { mgrs: "34VDN1760408035", lat: 60.499991, lon: 19.5 },
  { mgrs: "34VEN0000007097", lat: 60.499998, lon: 21.0 },
  { mgrs: "33VUJ6908076702", lat: 61.999994, lon: 12.5 },
  { mgrs: "33VWJ0000074180", lat: 61.999999, lon: 15.0 },
  { mgrs: "33VXJ4138977122", lat: 61.999997, lon: 17.699992 },
  { mgrs: "34VDP2143975088", lat: 61.999998, lon: 19.499998 },
  { mgrs: "34VEP0000074180", lat: 61.999999, lon: 21.0 },
  { mgrs: "33WUM7993355097", lat: 64.499998, lon: 12.499994 },
  { mgrs: "33WWM0000052732", lat: 64.499996, lon: 15.0 },
  { mgrs: "33WXM2966755490", lat: 64.499993, lon: 17.699984 },
  { mgrs: "34WDS2795053583", lat: 64.499993, lon: 19.499984 },
  { mgrs: "34WES0000052732", lat: 64.499996, lon: 21.0 },
  { mgrs: "33WUQ9101733569", lat: 66.999998, lon: 12.499978 },
  { mgrs: "33WWQ0000031380", lat: 66.999999, lon: 15.0 },
  { mgrs: "33WXQ1769633933", lat: 66.999996, lon: 17.699993 },
  { mgrs: "34WDV3460132168", lat: 66.999998, lon: 19.499988 },
  { mgrs: "34WEV0000031380", lat: 66.999999, lon: 21.0 },
  { mgrs: "33VXF6665179308", lat: 59.319631, lon: 17.928476 },
  { mgrs: "34VDM3756182883", lat: 60.277791, lon: 19.871059 },
];

test("MGRS→lat/lon matches the oracle across Swedish zones (<~2m)", () => {
  let maxErrDeg = 0;
  for (const o of ORACLE) {
    const got = mgrsToLatLon(o.mgrs);
    assert.ok(got, `failed to parse ${o.mgrs}`);
    const dLat = Math.abs(got!.lat - o.lat);
    const dLon = Math.abs(got!.lon - o.lon);
    maxErrDeg = Math.max(maxErrDeg, dLat, dLon);
    // ~2e-5 deg ≈ 2 m latitude; allow series-truncation/rounding slack.
    assert.ok(dLat < 5e-5, `${o.mgrs}: lat ${got!.lat} vs ${o.lat} (Δ${dLat})`);
    assert.ok(dLon < 1e-4, `${o.mgrs}: lon ${got!.lon} vs ${o.lon} (Δ${dLon})`);
  }
  assert.ok(maxErrDeg < 1e-4, `max error ${maxErrDeg} deg`);
});

test("accepts spaced grids and rejects non-grids", () => {
  const a = mgrsToLatLon("33VXF 66651 79308");
  const b = mgrsToLatLon("33VXF6665179308");
  assert.deepEqual(a, b);
  assert.equal(mgrsToLatLon("not a grid"), null);
  assert.equal(mgrsToLatLon("RJK241"), null);
});

test("findMgrsLatLon pulls a grid out of a Ställe blob", () => {
  const got = findMgrsLatLon("33VXF 66651 79308, Strandbacken, Höglandet");
  assert.ok(got && Math.abs(got.lat - 59.319631) < 1e-4);
});
